
name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install python and pip
        run: |
          sudo apt update -v
          sudo apt install python3 -y -v
          sudo apt install python3-pip
      - name: Install requirements
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Package for Linux
        run: pyinstaller panhunt.py -F --clean -i .\dionach.ico
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /home/runner/work/PANhunt/PANhunt/dist/panhunt
